-- Generated by src/00_refresh_prices.py on 2026-10-03.
-- Edit data/price_catalog.json, then re-run the refresh. Do not hand-edit this file.

INSERT INTO providers (name) VALUES
('Azure OpenAI'),
('AWS Bedrock'),
('GCP Vertex AI');

INSERT INTO models (provider_id, model_name, tier) VALUES
(1, 'GPT-4o', 'mid'),
(1, 'GPT-5', 'flagship'),
(1, 'GPT-4o-mini', 'budget'),
(2, 'Claude Sonnet 5', 'flagship'),
(2, 'Claude Sonnet 4.6', 'mid'),
(2, 'Claude Haiku 4.5', 'budget'),
(3, 'Gemini 3.1 Pro', 'flagship'),
(3, 'Gemini 2.5 Flash', 'mid');

INSERT INTO on_demand_pricing (model_id, input_per_mtok, output_per_mtok, effective_date, expires_date, source_url) VALUES
(1, 2.50, 10.00, '2026-10-03', NULL, 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service/'),
(2, 1.25, 10.00, '2026-10-03', NULL, 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service/'),
(3, 0.15, 0.60, '2026-10-03', NULL, 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service/'),
(4, 3.00, 15.00, '2026-10-03', NULL, 'https://aws.amazon.com/bedrock/pricing/'),
(5, 3.00, 15.00, '2026-10-03', NULL, 'https://aws.amazon.com/bedrock/pricing/'),
(6, 1.00, 5.00, '2026-10-03', NULL, 'https://aws.amazon.com/bedrock/pricing/'),
(7, 2.00, 12.00, '2026-10-03', NULL, 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(8, 0.30, 2.50, '2026-10-03', NULL, 'https://cloud.google.com/vertex-ai/generative-ai/pricing');

INSERT INTO committed_pricing (provider_id, model_id, unit_name, hourly_rate, term, tpm_capacity, throughput_note, effective_date, source_url) VALUES
(1, 1, 'PTU', 1.0000, 'hourly', 2500, 'Global PTU hourly. GPT-4o input TPM per PTU = 2,500 (Microsoft Learn).', '2026-10-03', 'https://azure.microsoft.com/en-us/blog/accelerate-scale-with-azure-openai-service-provisioned-offering/'),
(1, 1, 'PTU', 0.3562, '1-month', 2500, '1-month reservation $260/PTU-month / 730h.', '2026-10-03', 'https://azure.microsoft.com/en-us/blog/accelerate-scale-with-azure-openai-service-provisioned-offering/'),
(1, 1, 'PTU', 0.3027, '1-year', 2500, '1-year reservation $221/PTU-month / 730h.', '2026-10-03', 'https://azure.microsoft.com/en-us/blog/accelerate-scale-with-azure-openai-service-provisioned-offering/'),
(3, 8, 'GSU', 7.1429, '1-week', 161400, 'Published $1,200/GSU-week. 2,690 burndown tokens/sec per GSU.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 8, 'GSU', 3.6986, '1-month', 161400, 'Published $2,700/GSU-month. 2,690 burndown tokens/sec per GSU.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 8, 'GSU', 3.2877, '3-month', 161400, 'Published $2,400/GSU-month on a 3-month term.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 8, 'GSU', 2.7397, '1-year', 161400, 'Published $2,000/GSU-month on a 1-year term. About 26% under the 1-month rate.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 7, 'GSU', 3.6986, '1-month', 39000, 'Same GSU dollar price as Flash. Pro-class throughput uses the published Gemini 2.5 Pro rate of 650 burndown tokens/sec per GSU. Output tokens burn 8x.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/docs/provisioned-throughput/supported-models'),
(3, 7, 'GSU', 3.2877, '3-month', 39000, 'Published $2,400/GSU-month on a 3-month term. Pro-class 650 burndown tokens/sec. Output tokens burn 8x.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 7, 'GSU', 2.7397, '1-year', 39000, '1-year GSU. Pro-class 650 burndown tokens/sec. Output tokens burn 8x.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/docs/provisioned-throughput/supported-models');
