-- Generated by src/00_refresh_prices.py on 2026-10-03.
-- Edit data/price_catalog.json, then re-run the refresh. Do not hand-edit this file.

INSERT INTO providers (name) VALUES
('Azure OpenAI'),
('AWS Bedrock'),
('GCP Vertex AI');

INSERT INTO models (provider_id, model_name, tier) VALUES
(1, 'GPT-4o', 'mid'),
(1, 'GPT-5', 'flagship'),
(1, 'GPT-4o-mini', 'budget'),
(2, 'Claude Sonnet 5', 'flagship'),
(2, 'Claude Sonnet 4.6', 'mid'),
(2, 'Claude Haiku 4.5', 'budget'),
(3, 'Gemini 3.1 Pro', 'flagship'),
(3, 'Gemini 2.5 Flash', 'mid');

INSERT INTO on_demand_pricing (model_id, input_per_mtok, output_per_mtok, effective_date, expires_date, source_url) VALUES
(1, 2.50, 10.00, '2026-10-03', NULL, 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service/'),
(2, 1.25, 10.00, '2026-10-03', NULL, 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service/'),
(3, 0.15, 0.60, '2026-10-03', NULL, 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service/'),
(4, 3.00, 15.00, '2026-10-03', NULL, 'https://aws.amazon.com/bedrock/pricing/'),
(5, 3.00, 15.00, '2026-10-03', NULL, 'https://aws.amazon.com/bedrock/pricing/'),
(6, 1.00, 5.00, '2026-10-03', NULL, 'https://aws.amazon.com/bedrock/pricing/'),
(7, 2.00, 12.00, '2026-10-03', NULL, 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(8, 0.30, 2.50, '2026-10-03', NULL, 'https://cloud.google.com/vertex-ai/generative-ai/pricing');

INSERT INTO commitment_terms (provider_id, unit_name, term, hourly_rate, note, effective_date, source_url) VALUES
(1, 'PTU', 'hourly', 1.0000, 'Global PTU hourly, per PTU.', '2026-10-03', 'https://azure.microsoft.com/en-us/blog/accelerate-scale-with-azure-openai-service-provisioned-offering/'),
(1, 'PTU', '1-month', 0.3562, '$260/PTU-month / 730h.', '2026-10-03', 'https://azure.microsoft.com/en-us/blog/accelerate-scale-with-azure-openai-service-provisioned-offering/'),
(1, 'PTU', '1-year', 0.3027, '$221/PTU-month / 730h.', '2026-10-03', 'https://azure.microsoft.com/en-us/blog/accelerate-scale-with-azure-openai-service-provisioned-offering/'),
(3, 'GSU', '1-week', 7.1429, '$1,200/GSU-week.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 'GSU', '1-month', 3.6986, '$2,700/GSU-month.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 'GSU', '3-month', 3.2877, '$2,400/GSU-month, 3-month term.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing'),
(3, 'GSU', '1-year', 2.7397, '$2,000/GSU-month, 1-year term.', '2026-10-03', 'https://cloud.google.com/vertex-ai/generative-ai/pricing');

INSERT INTO unit_capacity (provider_id, unit_name, model_id, burndown_tpm, output_burn, note, source_url) VALUES
(1, 'PTU', 1, 2500, 4, 'Input TPM per PTU 2,500; 1 output token = 4 input tokens.', 'https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/provisioned-throughput-sizing'),
(1, 'PTU', 2, 4750, 8, 'Input TPM per PTU 4,750; 1 output token = 8 input tokens.', 'https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/provisioned-throughput-sizing'),
(1, 'PTU', 3, 37000, 4, 'Input TPM per PTU 37,000; 1 output token = 4 input tokens.', 'https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/provisioned-throughput-sizing'),
(3, 'GSU', 8, 161400, 9, '2,690 burndown tokens/sec x 60. Output burns 9x. <=200k context tier.', 'https://docs.cloud.google.com/vertex-ai/generative-ai/docs/provisioned-throughput/supported-models'),
(3, 'GSU', 7, 30000, 6, '500 burndown tokens/sec x 60. Output burns 6x. Preview model; <=200k context tier.', 'https://docs.cloud.google.com/vertex-ai/generative-ai/docs/provisioned-throughput/supported-models');
