"""Refresh the pricing seed from data/price_catalog.json and live provider pages.

Fetches each committed source URL and fails if none of the published price
needles are still on the page. Does not scrape dollar amounts out of JS
pricing widgets. --offline rewrites the seed without fetching.
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import DATA_DIR

CATALOG_PATH = DATA_DIR / "price_catalog.json"
SEED_PATH = DATA_DIR / "seed_pricing.sql"
SNAPSHOT_PATH = DATA_DIR / "price_snapshot.json"


def fetch(url: str) -> tuple[int, str]:
    req = urllib.request.Request(url, headers={"User-Agent": "llm-cost-lab/0.1"})
    with urllib.request.urlopen(req, timeout=25) as resp:
        return resp.status, resp.read(1_500_000).decode("utf-8", errors="replace")


def check_pages(catalog: dict, offline: bool) -> list[dict]:
    results = []
    urls = sorted({row["source_url"] for row in catalog["committed"]})
    for url in urls:
        needles = sorted({n for row in catalog["committed"] if row["source_url"] == url for n in row["needles"]})
        if offline:
            results.append({"url": url, "status": "skipped", "needles": needles, "hit": []})
            continue
        try:
            status, body = fetch(url)
        except (urllib.error.URLError, TimeoutError) as exc:
            results.append({"url": url, "status": f"error: {exc}", "needles": needles, "hit": [], "ok": False})
            continue
        hit = [n for n in needles if n in body]
        results.append({"url": url, "http": status, "needles": needles, "hit": hit, "ok": bool(hit)})
    return results


def q(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_seed(catalog: dict, fetched_on: str) -> None:
    providers = []
    for row in catalog["on_demand"]:
        if row["provider"] not in providers:
            providers.append(row["provider"])
    provider_id = {name: i + 1 for i, name in enumerate(providers)}
    model_id = {(row["provider"], row["model"]): i for i, row in enumerate(catalog["on_demand"], start=1)}
    lines = [
        f"-- Generated by src/00_refresh_prices.py on {fetched_on}.",
        "-- Edit data/price_catalog.json, then re-run the refresh. Do not hand-edit this file.",
        "",
        "INSERT INTO providers (name) VALUES",
        ",\n".join(f"({q(name)})" for name in providers) + ";",
        "",
        "INSERT INTO models (provider_id, model_name, tier) VALUES",
        ",\n".join(
            f"({provider_id[row['provider']]}, {q(row['model'])}, {q(row['tier'])})"
            for row in catalog["on_demand"]
        ) + ";",
        "",
        "INSERT INTO on_demand_pricing (model_id, input_per_mtok, output_per_mtok, effective_date, expires_date, source_url) VALUES",
        ",\n".join(
            f"({model_id[(r['provider'], r['model'])]}, {r['input_per_mtok']:.2f}, {r['output_per_mtok']:.2f}, {q(fetched_on)}, NULL, {q(r['source_url'])})"
            for r in catalog["on_demand"]
        ) + ";",
        "",
        "INSERT INTO committed_pricing (provider_id, model_id, unit_name, hourly_rate, term, tpm_capacity, throughput_note, effective_date, source_url) VALUES",
        ",\n".join(
            "("
            f"{provider_id[r['provider']]}, {model_id[(r['provider'], r['model'])]}, {q(r['unit_name'])}, "
            f"{r['hourly_rate']:.4f}, {q(r['term'])}, {r['tpm_capacity']}, {q(r['throughput_note'])}, {q(fetched_on)}, {q(r['source_url'])}"
            ")"
            for r in catalog["committed"]
        ) + ";\n",
    ]
    SEED_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    fetched_on = date.today().isoformat()
    checks = check_pages(catalog, args.offline)
    SNAPSHOT_PATH.write_text(json.dumps({"fetched_on": fetched_on, "offline": args.offline, "checks": checks}, indent=2), encoding="utf-8")
    write_seed(catalog, fetched_on)
    print(f"Wrote {SEED_PATH}")
    print(f"Wrote {SNAPSHOT_PATH}")
    for check in checks:
        print(f"  {check['url']} -> {check.get('status') or check.get('http')} hit={check['hit']}")
    if any(c.get("ok") is False for c in checks):
        raise SystemExit("Price needle missing on a live page. Seed was still rewritten from the catalog.")


if __name__ == "__main__":
    main()
